version: "2"
run:
  timeout: 5m
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
formatters:
  enable:
    - gofumpt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
